### PR TITLE
fix: fix known bugs in feat_bot

### PR DESCRIPTION
**Pull request by mmagi**
> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [x] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [x] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [x] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [x] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description

 fix known bugs in https://github.com/SonicCloudOrg/sonic-server/pull/345

### CODE REVIEW

**Review by ZhouYixun — COMMENTED** [review]
这几个文件辛苦format一下格式吧

**Review by ZhouYixun — APPROVED** [review]
感谢提交，辛苦了

**Comment by mmagi** [comment]
> 这几个文件辛苦format一下格式吧

变动部分基本都按IDEA的默认设置format过了，看还有哪个不符合习惯的我再单独改一下？

**Comment by ZhouYixun** [comment]
image

这里是不是漏了format

**Comment by mmagi** [comment]
> image
> 
> 这里是不是漏了format

已更正，感谢指出

**Pull request merged**
